services:
  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: alexandria
      MARIADB_USER: alexandria
      MARIADB_PASSWORD: alexandria
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../database/data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    platform: linux/amd64
    image: ksenishl/alexandria:1.0.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      DISPLAY: host.docker.internal:0.0
    volumes:
      - ${HOST_FILES_DIR}:/host:ro
      - alexandria_uploads:/app/uploads
    command:
      [
        "java",
        "-Ddb.url=jdbc:mariadb://db:3306/alexandria",
        "-Ddb.user=alexandria",
        "-Ddb.password=alexandria",
        "-Dalexandria.file.chooser.dir=/host",
        "--module-path",
        "/javafx-sdk/lib",
        "--add-modules",
        "javafx.controls,javafx.fxml,javafx.swing",
        "-jar",
        "app.jar"
      ]

volumes:
  mariadb_data:
  alexandria_uploads:
